In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### why lines?

In [ ]:
data60 = pd.read_csv('datafilm/r6/r6smo0.dat',skiprows=1)
data61 = pd.read_csv('datafilm/r6/r6smo1.dat',skiprows=1)
data62 = pd.read_csv('datafilm/r6/r6smo2.dat',skiprows=1)

data70 = pd.read_csv('datafilm/r7/r7smo0.dat',skiprows=1)
data71 = pd.read_csv('datafilm/r7/r7smo1.dat',skiprows=1)
data72 = pd.read_csv('datafilm/r7/r7smo2.dat',skiprows=1)

data80 = pd.read_csv('datafilm/r8/r8smo0.dat',skiprows=1)
data81 = pd.read_csv('datafilm/r8/r8smo1.dat',skiprows=1)
data82 = pd.read_csv('datafilm/r8/r8smo2.dat',skiprows=1)

data90 = pd.read_csv('datafilm/r9/r9smo0.dat',skiprows=1)
data91 = pd.read_csv('datafilm/r9/r9smo1.dat',skiprows=1)
data92 = pd.read_csv('datafilm/r9/r9smo2.dat',skiprows=1)

data100 = pd.read_csv('datafilm/r10/r10smo0.dat',skiprows=1)
data101 = pd.read_csv('datafilm/r10/r10smo1.dat',skiprows=1)
data102 = pd.read_csv('datafilm/r10/r10smo2.dat',skiprows=1)

data110 = pd.read_csv('datafilm/r11/r11smo0.dat',skiprows=1)
data111 = pd.read_csv('datafilm/r11/r11smo1.dat',skiprows=1)
data112 = pd.read_csv('datafilm/r11/r11smo2.dat',skiprows=1)

In [ ]:
def getdt(data):
    dt = np.diff(data['Time'])
    fig, (ax1,ax2) = plt.subplots(1,2,figsize=(12,4))
    ax1.plot(data['Time'][1:], dt, 'm.-', markersize=3)
    ax1.set_ylabel('Δt (сек)')
    ax1.set_xlabel('Время (t)')
    ax1.grid(True)
    ax2.plot(data['Time'][1:], dt, 'g.-', markersize=3)
    ax2.set_yscale('log')
    ax2.set_xlabel('Время (t)')
    ax2.set_ylabel('Δt (лог. шкала)')
    ax2.grid(True)
    plt.tight_layout()
    plt.show()

### there is linear interpolating

In [15]:
def interpol(data, number):
    tstart = data['Time'].iloc[0]
    tend = data['Time'].iloc[-1]
    dt = 0.001

    regular_times = list(np.arange(tstart, tend + dt, dt))
    regular_data = pd.DataFrame({'Time': regular_times})

    for col in data.columns[1:]:
        init_times = data['Time'].values
        init_heights = data[col].values
        interp = []
        idx = 0
        
        for treg in regular_times:
            while idx < len(init_times) - 1 and init_times[idx + 1] < treg:
                idx += 1
            
            # Интерполяция
            if idx == len(init_times) - 1:
                interp.append(init_heights[idx])
            else:
                t1, t2 = init_times[idx], init_times[idx + 1]
                h1, h2 = init_heights[idx], init_heights[idx + 1]
                # Проверка, что treg в интервале
                if t1 <= treg <= t2:
                    h_interp = h1 + (h2 - h1) * (treg - t1) / (t2 - t1)
                else:
                    # Если из-за погрешности treg чуть больше t2
                    h_interp = init_heights[idx]
                interp.append(h_interp)
        
        regular_data[col] = interp

    regular_data.to_csv(f'regular_data{number}v1.txt', sep=',', index=False, float_format='%.10E')
    return regular_data

In [16]:
data121 = pd.read_csv('datafilm/r12/r12smo1_v1.dat',skiprows=[0])
interpol(data121,121)

C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp
C:\Users\giper\AppData\Local\Temp\ipykernel_13616\811853194.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  regular_data[col] = interp

,Time,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,N4491,N4492,N4493,N4494,N4495,N4496,N4497,N4498,N4499,N4500
0,0.000989,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,...,0.000194,0.000194,0.000195,0.000195,0.000195,0.000195,0.000196,0.000196,0.000196,0.000196
1,0.001989,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,...,0.000194,0.000195,0.000195,0.000195,0.000196,0.000196,0.000196,0.000196,0.000196,0.000197
2,0.002989,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,...,0.000195,0.000195,0.000195,0.000196,0.000196,0.000196,0.000196,0.000197,0.000197,0.000197
3,0.003989,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000194,0.000194,0.000194,...,0.000195,0.000195,0.000195,0.000196,0.000196,0.000196,0.000196,0.000197,0.000197,0.000197
4,0.004989,0.000193,0.000193,0.000193,0.000193,0.000193,0.000194,0.000194,0.000194,0.000194,...,0.000195,0.000195,0.000195,0.000196,0.000196,0.000196,0.000196,0.000197,0.000197,0.000197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,0.818989,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000194,0.000194,...,0.000196,0.000196,0.000197,0.000197,0.000197,0.000197,0.000197,0.000197,0.000197,0.000198
819,0.819989,0.000192,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,...,0.000198,0.000199,0.000199,0.000199,0.000199,0.000199,0.000199,0.000199,0.000199,0.000199
820,0.820989,0.000192,0.000192,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,0.000193,...,0.000196,0.000196,0.000196,0.000197,0.000197,0.000197,0.000197,0.000197,0.000197,0.000197
821,0.821989,0.000192,0.000192,0.000192,0.000192,0.000192,0.000193,0.000193,0.000193,0.000193,...,0.000188,0.000189,0.000189,0.000189,0.000190,0.000190,0.000190,0.000190,0.000190,0.000190
822,0.822989,0.000192,0.000192,0.000192,0.000192,0.000192,0.000193,0.000193,0.000193,0.000193,...,0.000188,0.000189,0.000189,0.000189,0.000190,0.000190,0.000190,0.000190,0.000190,0.000190

In [18]:
data = pd.read_csv("coordinates.csv")
data

    Index  Pixel_X  Pixel_Y  Real_X   Real_Y
0       1    180.0    302.0  3.1524  43.2331
1       2    192.0    297.0  3.3625  44.1729
2       3    201.0    289.0  3.5201  45.6767
3       4    231.0    274.0  4.0455  48.4962
4       5    237.0    268.0  4.1506  49.6241
5       6    268.0    245.0  4.6935  53.9474
6       7    343.0    183.0  6.0070  65.6015
7       8    377.0    158.0  6.6025  70.3008
8       9    420.0    122.0  7.3555  77.0677
9      10    180.0    325.0  3.1524  38.9098
10     11    192.0    321.0  3.3625  39.6617
11     12    199.0    322.0  3.4851  39.4737
12     13    227.0    307.0  3.9755  42.2932
13     14    238.0    302.0  4.1681  43.2331
14     15    268.0    276.0  4.6935  48.1203
15     16    343.0    200.0  6.0070  62.4060
16     17    378.0    186.0  6.6200  65.0376
17     18    420.0    157.0  7.3555  70.4887
18     19    179.0    369.0  3.1349  30.6391
19     20    192.0    365.0  3.3625  31.3910
20     21    201.0    363.0  3.5201  31.7669
21     22    227.0    350.0  3.9755  34.2105
22     23    236.0    343.0  4.1331  35.5263
23     24    268.0    336.0  4.6935  36.8421
24     25    345.0    287.0  6.0420  46.0526
25     26    377.0    277.0  6.6025  47.9323
26     27    418.0    270.0  7.3205  49.2481